spring:
  application:
    name: tracker-models

  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: task_tracker

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/*.yaml
    default-schema: task_tracker
