server:
  port: 9090

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: task_tracker
  jpa:
    show-sql: true


  liquibase:
    enabled: false

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    liquibase: DEBUG
